from typing import Annotated, Optional
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    instrument_context: Annotated[str, "Deterministic ticker identity resolved at run start"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]

    # Single source of truth for financials (A1) — computed once in Python at
    # run start, injected into every number-touching agent (cite-only).
    financials_block: Annotated[str, "Canonical financial data block (single source of truth)"]
    financials_chart_json: Annotated[str, "VN_CHART_DATA JSON for render_report charts"]

    # Risk metrics deterministic (Task 10 R1) — beta/VaR/drawdown/ADTV/days-to-liquidate
    # tính từ price history ở run start, inject vào 3 risk debator.
    risk_metrics_block: Annotated[str, "Deterministic risk metrics block for risk analysts"]

    # Grounded fact-check gate (Round 3 C1-C5)
    company_profile_block: Annotated[str, "Company profile from vnstock (C5 ground truth for entity verification)"]
    fact_check_corrections: Annotated[str, "Corrections from C3 gate: contradicted/unverified entity claims"]
    verified_entity_claims: Annotated[str, "JSON array of entity claims with verdicts (C1/C2 output)"]

    # Phase-I structured ratings (Round 5 E3) — PortfolioRating value string or None.
    # Set by a second lightweight LLM call after each analyst's prose report is done.
    # None means the extraction was skipped or failed — render as "chưa có dữ liệu".
    market_analyst_rating: Annotated[Optional[str], "Structured rating from Market Analyst (AnalystSignal.recommendation)"]
    news_analyst_rating: Annotated[Optional[str], "Structured rating from News Analyst"]
    fundamentals_analyst_rating: Annotated[Optional[str], "Structured rating from Fundamentals Analyst"]
    market_analyst_reason: Annotated[Optional[str], "One-sentence reason from Market Analyst (AnalystSignal.reasoning_summary)"]
    news_analyst_reason: Annotated[Optional[str], "One-sentence reason from News Analyst"]
    fundamentals_analyst_reason: Annotated[Optional[str], "One-sentence reason from Fundamentals Analyst"]
    # Phase-II/III/V structured ratings — extracted from typed Pydantic objects at agent runtime.
    # Eliminates fragile regex re-extraction at render time for RM, Trader, PM.
    rm_rating: Annotated[Optional[str], "Structured rating from Research Manager (ResearchPlan.recommendation)"]
    rm_reason: Annotated[Optional[str], "Rationale from Research Manager (ResearchPlan.rationale)"]
    trader_rating: Annotated[Optional[str], "Structured rating from Trader (TraderProposal.action)"]
    trader_reason: Annotated[Optional[str], "Reasoning from Trader (TraderProposal.reasoning)"]
    pm_rating: Annotated[Optional[str], "Structured rating from Portfolio Manager (PortfolioDecision.rating)"]
    pm_reason: Annotated[Optional[str], "Executive summary from Portfolio Manager (PortfolioDecision.executive_summary)"]
